### ISSUE TITLE
Not quite working?  Can't install to Unity...

### ISSUE THREAD

**Issue by zipzit** [jeffjadulco/unity-guid-regenerator#3]
Unity version 2019.4.18f1 Personal 
Win10 Home

Package manager tab, then + Add Package from URL, Paste:   `https://github.com/jeffjadulco/unity-guid-regenerator/releases/tag/1.0.1`

`Error Adding Package, UnityEditor.EditorApplication:Internal_CallUpdateFunctions()  `

Download to local hard drive, then Package manager tab + Add Package from Disk  (the program seems to be looking for .json files...)  If I force `unity-guid-regenerator@1.0.1.unitypackage`, it just fails.  

Am I doing  this right?  I'm trying to follow the instructions on the readme.md, but there appears to be something missing.. Many thanks.

**Comment by jeffjadulco** [comment]
When I started this project, I had no idea you could actually import packages from a git repo. Though it requires a setup and rearranging the directory, I can make it work for future users. 

But right now you can manually download the package in the releases tab: https://github.com/jeffjadulco/unity-guid-regenerator/releases

Then import the package manually in Unity Editor.

**Comment by zipzit** [comment]
No problem. I was finally able to get your program to run, directly, from the download.  with that said, your program doesn't address folders.  

My use case was utterly moronic.  I was trying to clone Scene1 into Scene2 and Scene3 by simply copy/paste in Windows File Explorer.  Not clever.  Much easier to work in Unity, copy content in Unity development tool, create new Scene, then paste.  Repeat.  

But with that said, perhaps some simple improvements to the `readme` might be appropriate.  (Why would you want to use this tool, possible use cases, etc...  Perhaps a warning to those of us on the wrong side of reality?  :)   Many thanks for sharing your work as open source.

**Comment by jeffjadulco** [comment]
I see, yeah for that use case it's much easier to just duplicate the scenes inside Unity. Dealing with scenes using this tool is kinda dangerous because scenes do reference a lot of objects. It is also in the readme that scene files are skipped because changing the scene's guid corrupts it. 

Thanks for the feedback about the readme, will definitely improve its contents and add some use cases. :)

**Comment by jeffjadulco** [comment]
Installation via UPM (Unity Package Manager) is now supported. 

Commit b623824bccf62171a7a9d49dcfee2bc001965c62 closes #3
